"""
Static vehicle catalog — 28 models across 7 brands.
"""

from __future__ import annotations

from dataclasses import dataclass, field


@dataclass(frozen=True)
class VehicleSpec:
    make: str
    model: str
    segment: str
    msrp_low: int
    msrp_high: int
    annual_depreciation_rate: float
    popularity_weight: float
    reliability_score: float
    avg_days_on_lot: int
    typical_buyer_age_mean: float
    typical_buyer_age_std: float
    available_colors: tuple[str, ...] = field(default=("White", "Black", "Silver", "Gray", "Blue", "Red"))
    available_trims: tuple[str, ...] = field(default=("Base", "Mid", "Premium"))

    def msrp_midpoint(self) -> float:
        return (self.msrp_low + self.msrp_high) / 2.0

    def depreciated_value(self, age_years: float, mileage: int) -> float:
        base = self.msrp_midpoint()
        age_factor = (1.0 - self.annual_depreciation_rate) ** age_years
        expected_miles = age_years * 12_000
        excess_miles = max(0, mileage - expected_miles)
        mileage_penalty = excess_miles * 0.08
        return max(base * age_factor - mileage_penalty, base * 0.10)


VEHICLE_CATALOG: list[VehicleSpec] = [
    # TOYOTA
    VehicleSpec(
        "Toyota",
        "Camry",
        "Sedan",
        26420,
        35720,
        0.155,
        1.40,
        0.89,
        22,
        42.0,
        11.0,
        ("White", "Black", "Silver", "Gray", "Red", "Blue"),
        ("LE", "SE", "XSE", "XLE"),
    ),
    VehicleSpec(
        "Toyota",
        "RAV4",
        "SUV",
        28475,
        40760,
        0.145,
        1.65,
        0.91,
        18,
        38.0,
        10.0,
        ("White", "Black", "Gray", "Blue", "Red", "Green"),
        ("LE", "XLE", "Adventure", "Limited", "TRD Off-Road"),
    ),
    VehicleSpec(
        "Toyota",
        "Tacoma",
        "Truck",
        28700,
        44910,
        0.110,
        1.35,
        0.87,
        15,
        35.0,
        9.0,
        ("White", "Black", "Silver", "Gray", "Red", "Army Green"),
        ("SR", "SR5", "TRD Sport", "TRD Off-Road", "Limited"),
    ),
    VehicleSpec("Toyota", "Highlander", "SUV", 36420, 52875, 0.160, 1.10, 0.88, 24, 44.0, 9.5),
    # HONDA
    VehicleSpec(
        "Honda",
        "Accord",
        "Sedan",
        27295,
        38640,
        0.160,
        1.25,
        0.88,
        25,
        40.0,
        12.0,
        ("White", "Black", "Silver", "Gray", "Blue", "Red"),
        ("LX", "Sport", "EX-L", "Touring"),
    ),
    VehicleSpec(
        "Honda",
        "CR-V",
        "SUV",
        29400,
        39200,
        0.150,
        1.45,
        0.90,
        20,
        37.0,
        10.0,
        ("White", "Black", "Silver", "Gray", "Blue", "Red"),
        ("LX", "EX", "EX-L", "Sport", "Touring"),
    ),
    VehicleSpec(
        "Honda",
        "Pilot",
        "SUV",
        38050,
        51200,
        0.165,
        0.90,
        0.85,
        28,
        43.0,
        8.5,
        ("White", "Black", "Silver", "Gray", "Blue", "Red"),
        ("Sport", "EX-L", "TrailSport", "Elite"),
    ),
    VehicleSpec(
        "Honda",
        "Civic",
        "Sedan",
        23950,
        31900,
        0.170,
        1.20,
        0.87,
        21,
        29.0,
        8.0,
        ("White", "Black", "Silver", "Blue", "Red", "Sonic Gray"),
        ("LX", "Sport", "EX", "Touring"),
    ),
    # FORD
    VehicleSpec(
        "Ford",
        "F-150",
        "Truck",
        32145,
        79840,
        0.175,
        1.80,
        0.78,
        16,
        41.0,
        11.0,
        ("White", "Black", "Silver", "Gray", "Blue", "Red", "Rapid Red"),
        ("Regular", "XL", "XLT", "Lariat", "Platinum", "Limited", "Raptor"),
    ),
    VehicleSpec(
        "Ford",
        "Explorer",
        "SUV",
        36760,
        56600,
        0.190,
        1.10,
        0.74,
        30,
        43.0,
        9.0,
        ("White", "Black", "Silver", "Gray", "Blue", "Red"),
        ("Base", "XLT", "ST", "Limited", "Platinum"),
    ),
    VehicleSpec(
        "Ford",
        "Mustang",
        "Coupe",
        30920,
        59900,
        0.200,
        0.70,
        0.73,
        38,
        34.0,
        13.0,
        ("White", "Black", "Gray", "Red", "Blue", "Yellow", "Orange"),
        ("EcoBoost", "GT", "Mach 1", "Shelby GT500"),
    ),
    VehicleSpec(
        "Ford",
        "Bronco",
        "SUV",
        33695,
        65390,
        0.125,
        0.85,
        0.76,
        19,
        36.0,
        9.5,
        ("White", "Black", "Gray", "Blue", "Red", "Green"),
        ("Base", "Big Bend", "Black Diamond", "Outer Banks", "Badlands", "Wildtrak", "Raptor"),
    ),
    # CHEVROLET
    VehicleSpec(
        "Chevrolet",
        "Silverado 1500",
        "Truck",
        34600,
        72000,
        0.180,
        1.55,
        0.77,
        18,
        42.0,
        11.5,
        ("White", "Black", "Silver", "Gray", "Blue", "Red", "Green"),
        ("Work Truck", "Custom", "LT", "RST", "LTZ", "High Country", "ZR2"),
    ),
    VehicleSpec(
        "Chevrolet",
        "Equinox",
        "SUV",
        26600,
        37100,
        0.185,
        1.15,
        0.80,
        26,
        38.0,
        11.0,
        ("White", "Black", "Silver", "Gray", "Blue", "Red"),
        ("LS", "LT", "RS", "Premier"),
    ),
    VehicleSpec(
        "Chevrolet",
        "Traverse",
        "SUV",
        35400,
        53200,
        0.195,
        0.85,
        0.79,
        29,
        44.0,
        8.5,
        ("White", "Black", "Silver", "Gray", "Blue", "Red"),
        ("LS", "LT", "RS", "Premier", "High Country"),
    ),
    VehicleSpec(
        "Chevrolet",
        "Colorado",
        "Truck",
        27200,
        46500,
        0.160,
        0.80,
        0.81,
        22,
        37.0,
        10.0,
        ("White", "Black", "Silver", "Gray", "Blue", "Red"),
        ("WT", "LT", "Z71", "ZR2"),
    ),
    # NISSAN
    VehicleSpec(
        "Nissan",
        "Rogue",
        "SUV",
        27860,
        38510,
        0.195,
        1.20,
        0.79,
        26,
        38.0,
        10.5,
        ("White", "Black", "Silver", "Gray", "Blue", "Red"),
        ("S", "SV", "SL", "Platinum"),
    ),
    VehicleSpec(
        "Nissan",
        "Frontier",
        "Truck",
        29940,
        42680,
        0.150,
        0.75,
        0.82,
        24,
        39.0,
        10.0,
        ("White", "Black", "Silver", "Gray", "Blue", "Red"),
        ("S", "SV", "Pro-4X", "PRO-X", "SL"),
    ),
    VehicleSpec(
        "Nissan",
        "Altima",
        "Sedan",
        24300,
        34250,
        0.200,
        0.95,
        0.77,
        30,
        36.0,
        12.0,
        ("White", "Black", "Silver", "Gray", "Blue", "Red"),
        ("S", "SV", "SR", "SL", "Platinum"),
    ),
    VehicleSpec("Nissan", "Pathfinder", "SUV", 34175, 51925, 0.185, 0.70, 0.76, 31, 45.0, 9.0),
    # HYUNDAI
    VehicleSpec(
        "Hyundai",
        "Tucson",
        "SUV",
        27050,
        38950,
        0.185,
        1.00,
        0.83,
        27,
        37.0,
        10.5,
        ("White", "Black", "Silver", "Gray", "Blue", "Red", "Green"),
        ("SE", "SEL", "N Line", "Limited"),
    ),
    VehicleSpec(
        "Hyundai",
        "Santa Fe",
        "SUV",
        32600,
        45100,
        0.180,
        0.85,
        0.84,
        28,
        42.0,
        9.0,
        ("White", "Black", "Silver", "Gray", "Blue", "Red"),
        ("SE", "SEL", "XRT", "Limited", "Calligraphy"),
    ),
    VehicleSpec(
        "Hyundai",
        "Elantra",
        "Sedan",
        21950,
        30650,
        0.190,
        0.90,
        0.85,
        24,
        30.0,
        9.0,
        ("White", "Black", "Silver", "Gray", "Blue", "Red", "Yellow"),
        ("SE", "SEL", "N Line", "Limited"),
    ),
    VehicleSpec(
        "Hyundai",
        "Palisade",
        "SUV",
        35850,
        52300,
        0.175,
        0.75,
        0.86,
        25,
        45.0,
        8.5,
        ("White", "Black", "Silver", "Gray", "Blue", "Red"),
        ("SE", "SEL", "XRT", "Limited", "Calligraphy"),
    ),
    # JEEP
    VehicleSpec(
        "Jeep",
        "Grand Cherokee",
        "SUV",
        38995,
        74995,
        0.200,
        1.05,
        0.70,
        32,
        42.0,
        10.0,
        ("White", "Black", "Gray", "Blue", "Red", "Green", "Hydro Blue"),
        ("Laredo", "Altitude", "Limited", "Overland", "Summit", "Trailhawk", "4xe"),
    ),
    VehicleSpec(
        "Jeep",
        "Wrangler",
        "SUV",
        31195,
        58300,
        0.130,
        1.10,
        0.68,
        20,
        35.0,
        11.0,
        ("White", "Black", "Gray", "Blue", "Red", "Green", "Orange", "Yellow"),
        ("Sport", "Sport S", "Willys", "Sahara", "Rubicon", "392"),
    ),
    VehicleSpec(
        "Jeep",
        "Compass",
        "SUV",
        24695,
        35090,
        0.210,
        0.65,
        0.69,
        36,
        33.0,
        10.0,
        ("White", "Black", "Gray", "Blue", "Red", "Green"),
        ("Sport", "Latitude", "Longitude", "Limited", "Trailhawk"),
    ),
    VehicleSpec(
        "Jeep",
        "Gladiator",
        "Truck",
        37995,
        57500,
        0.155,
        0.60,
        0.71,
        34,
        38.0,
        10.5,
        ("White", "Black", "Gray", "Blue", "Red", "Green"),
        ("Sport", "Sport S", "Willys", "Overland", "Rubicon", "Mojave"),
    ),
]


def popularity_weights() -> list[float]:
    raw = [s.popularity_weight for s in VEHICLE_CATALOG]
    total = sum(raw)
    return [w / total for w in raw]
